import { TreeNodeData } from "./layout-engine";

export const MOCK_NODES: TreeNodeData[] = [
  // ====== รุ่นที่ 1 ======
  {
    id: "node-1",
    parentId: null,
    nickname: "เจมส์",
    firstName: "สมชาย",
    lastName: "ใจดี",
    studentId: "6101001",
    generation: 1,
    photoUrl: "",
    status: "graduated",
    siblingOrder: 0,
  },

  // ====== รุ่นที่ 2 ======
  {
    id: "node-2",
    parentId: "node-1",
    nickname: "มิ้นท์",
    firstName: "สมหญิง",
    lastName: "ดีใจ",
    studentId: "6201001",
    generation: 2,
    photoUrl: "",
    status: "graduated",
    siblingOrder: 0,
  },
  {
    id: "node-3",
    parentId: "node-1",
    nickname: "บีม",
    firstName: "สมศักดิ์",
    lastName: "มีสุข",
    studentId: "6201002",
    generation: 2,
    photoUrl: "",
    status: "graduated",
    siblingOrder: 1,
  },
  {
    id: "node-4",
    parentId: "node-1",
    nickname: "แพร",
    firstName: "สมปอง",
    lastName: "รักเรียน",
    studentId: "6201003",
    generation: 2,
    photoUrl: "",
    status: "graduated",
    siblingOrder: 2,
  },

  // ====== รุ่นที่ 3 ======
  {
    id: "node-5",
    parentId: "node-2",
    nickname: "นิว",
    firstName: "ใหม่",
    lastName: "สดใส",
    studentId: "6301001",
    generation: 3,
    photoUrl: "",
    status: "studying",
    siblingOrder: 0,
  },
  {
    id: "node-6",
    parentId: "node-2",
    nickname: "เฟิร์น",
    firstName: "เฟิร์น",
    lastName: "ชื่นใจ",
    studentId: "6301002",
    generation: 3,
    photoUrl: "",
    status: "studying",
    siblingOrder: 1,
  },
  {
    id: "node-7",
    parentId: "node-3",
    nickname: "ไอซ์",
    firstName: "เย็น",
    lastName: "สบาย",
    studentId: "6301003",
    generation: 3,
    photoUrl: "",
    status: "studying",
    siblingOrder: 0,
  },

  // ====== รุ่นที่ 4 ======
  {
    id: "node-8",
    parentId: "node-5",
    nickname: "ออม",
    firstName: "ออมสิน",
    lastName: "มีทรัพย์",
    studentId: "6401001",
    generation: 4,
    photoUrl: "",
    status: "studying",
    siblingOrder: 0,
  },
  {
    id: "node-9",
    parentId: "node-5",
    nickname: "พลอย",
    firstName: "พลอยใส",
    lastName: "แวววาว",
    studentId: "6401002",
    generation: 4,
    photoUrl: "",
    status: "studying",
    siblingOrder: 1,
  },
  {
    id: "node-10",
    parentId: "node-7",
    nickname: "ฟลุ๊ค",
    firstName: "โชคดี",
    lastName: "มีชัย",
    studentId: "6401003",
    generation: 4,
    photoUrl: "",
    status: "studying",
    siblingOrder: 0,
  },
];